name = "automationa-tools-local"
compatibility_date = "2023-06-28"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "out"

# ローカル開発用の共通変数
[vars]
APP_NAME = "Automationa Tools Local"
ENVIRONMENT = "local"
DATABASE = "local"
NODE_ENV = "development"

# ローカル開発用のD1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "automationa-tools-local-db"
database_id = "${D1_DATABASE_ID}" # 環境変数から読み込み
migrations_dir = "migrations"

# ローカル開発用のKVネームスペース設定
[[kv_namespaces]]
binding = "CACHE_DEV"  # ローカル環境用キャッシュバインディング
id = "${KV_CACHE_ID}"

[[kv_namespaces]]
binding = "SESSION_STORE_DEV"  # ローカル環境用セッションストアバインディング
id = "${KV_SESSION_STORE_ID}"

# ローカル開発用のR2バケット設定
[[r2_buckets]]
binding = "R2_ASSETS"  # ローカル環境アセットストレージ
bucket_name = "${R2_ASSETS_BUCKET_NAME}"

[[r2_buckets]]
binding = "R2_BACKUPS"  # ローカル環境バックアップストレージ
bucket_name = "${R2_BACKUPS_BUCKET_NAME}"

# 注意：
# - ローカル開発: `pnpm exec wrangler dev --config wrangler-local.toml`