name = "automationa-tools"
# mainを削除（Pagesではサポートされていない）
compatibility_date = "2023-06-28"
compatibility_flags = [ "nodejs_compat" ]
# workers_devを削除
# pages_build_output_dirの代わりにpages_build_output_dirを使用
pages_build_output_dir = "out"  # Cloudflare Pagesのビルド出力ディレクトリ
# ビルドコマンド
build.command = "pnpm run build"

# ローカル開発用の共通変数
[vars]
APP_NAME = "Automationa Tools Local"
ENVIRONMENT = "local"
DATABASE = "local"
NODE_ENV = "development"

# ローカル開発用のD1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "automationa-tools-local-db"
database_id = "${D1_DATABASE_ID}" # 環境変数から読み込み
migrations_dir = "migrations"

# ローカル開発用のKVネームスペース設定
[[kv_namespaces]]
binding = "CACHE_DEV"  # ローカル環境用キャッシュバインディング
id = "${KV_CACHE_ID}"

[[kv_namespaces]]
binding = "SESSION_STORE_DEV"  # ローカル環境用セッションストアバインディング
id = "${KV_SESSION_STORE_ID}"

# ローカル開発用のR2バケット設定
[[r2_buckets]]
binding = "R2_ASSETS"  # ローカル環境アセットストレージ
bucket_name = "${R2_ASSETS_BUCKET_NAME}"

[[r2_buckets]]
binding = "R2_BACKUPS"  # ローカル環境バックアップストレージ
bucket_name = "${R2_BACKUPS_BUCKET_NAME}"

# ===========================================================
# ローカル環境設定（env.local）
# ===========================================================
[env.local]
env_path = ".env.local"  # ローカル開発用の環境変数ファイル

# 環境変数設定（ローカル）
[env.local.vars]
APP_NAME = "Automationa Tools Local"
ENVIRONMENT = "local"
DATABASE = "local"
NODE_ENV = "development"

# ===========================================================
# 本番環境（production）設定
# ===========================================================
[env.production]
env_path = ".env.production"

# 環境変数設定（プロダクション）
[env.production.vars]
APP_NAME = "Automationa Tools"
ENVIRONMENT = "production"
DATABASE = "prod"
NODE_ENV = "production"

# D1データベース設定（プロダクション）
[[env.production.d1_databases]]
binding = "DB"  # バインディング名
database_name = "${D1_DATABASE_NAME}"  # 環境変数から読み込み
database_id = "${D1_DATABASE_ID}"
migrations_dir = "migrations"

# KVネームスペース設定（プロダクション）
[[env.production.kv_namespaces]]
binding = "CACHE_PROD"  # 本番環境用キャッシュバインディング
id = "${KV_CACHE_ID}"

[[env.production.kv_namespaces]]
binding = "SESSION_STORE_PROD"  # 本番環境用セッションストアバインディング
id = "${KV_SESSION_STORE_ID}"

# R2バケット設定（プロダクション）
[[env.production.r2_buckets]]
binding = "R2_ASSETS"  # 本番環境アセットストレージ
bucket_name = "${R2_ASSETS_BUCKET_NAME}"

[[env.production.r2_buckets]]
binding = "R2_BACKUPS"  # 本番環境バックアップストレージ
bucket_name = "${R2_BACKUPS_BUCKET_NAME}"

# ===========================================================
# 開発環境（preview）設定
# ===========================================================
[env.preview]
env_path = ".env.preview"

# 環境変数設定（プレビュー）
[env.preview.vars]
APP_NAME = "automationa-tools-preview"
ENVIRONMENT = "preview"
DATABASE = "preview"
NODE_ENV = "development"

# D1データベース設定（プレビュー）
[[env.preview.d1_databases]]
binding = "DB"  # バインディング名
database_name = "${D1_DATABASE_NAME}"  # 環境変数から読み込み
database_id = "${D1_DATABASE_ID}"
migrations_dir = "migrations"

# KVネームスペース設定（プレビュー）
[[env.preview.kv_namespaces]]
binding = "CACHE_DEV"  # 開発環境用キャッシュバインディング
id = "${KV_CACHE_ID}"

[[env.preview.kv_namespaces]]
binding = "SESSION_STORE_DEV"  # 開発環境用セッションストアバインディング
id = "${KV_SESSION_STORE_ID}"

# R2バケット設定（プレビュー）
[[env.preview.r2_buckets]]
binding = "R2_ASSETS"  # 開発環境アセットストレージ
bucket_name = "${R2_ASSETS_BUCKET_NAME}"

[[env.preview.r2_buckets]]
binding = "R2_BACKUPS"  # 開発環境バックアップストレージ
bucket_name = "${R2_BACKUPS_BUCKET_NAME}"

# .envファイルは、各環境に対応する env_path で自動的に読み込まれます：
# - production: .env.production (pnpm exec wrangler pages deploy --env=production)
# - preview: .env.preview (pnpm exec wrangler pages dev --env=preview)
# - local: .env.local (pnpm exec wrangler pages dev --env=local)

# 注意: ローカル環境はCloudflare Pagesデプロイには使用されません
# ローカル開発時のみ使用されます

# 注意：
# - ローカル開発: `pnpm exec wrangler pages dev out` （出力ディレクトリを指定）
# - プレビューデプロイ: `pnpm exec wrangler pages deploy --env=preview`
# - 本番デプロイ: `pnpm exec wrangler pages deploy --env=production`